### ISSUE TITLE
[1.18] Riptide Elder Trident doesn't work

### ISSUE THREAD

**Issue by Desempregago** [Ladysnake/Impaled#11]
https://user-images.githubusercontent.com/14002834/145644312-879995a6-481c-4577-beab-72022da9d56b.mp4

Impaled 1.0.2

**Comment by Xiribidus** [comment]
You have to be in water to use riptide in general

**Comment by Desempregago** [comment]
Oh yeah, forgot about it lmao :P

**Comment by Desempregago** [comment]
Yeah, but wouldn't I be at least able to THROW it?

**Comment by Xiribidus** [comment]
No, that is vanilla design. As soon as a trident has riptide it cannot be thrown anymore.

**Comment by MoriyaShiine** [comment]
vanilla lol
