### ISSUE TITLE
Backport Request: Backport mod to 1.16.5

### ISSUE THREAD

**Issue by Shibva** [Ladysnake/Impaled#12]
This is a great mod, and it has a great potential for adding more tridants, shame though the number of mods that add more variants of them are limited. It would be nice to see these guys in 1.16.5 as well if its possable

**Comment by MaxwellRU** [comment]
me too! also I wood like to add this mod to the pack I'm making..

**Comment by Shibva** [comment]
yeah, and is this exit in forge?

**Comment by MaxwellRU** [comment]
> yeah, and is this exit in forge?
pack? yep.. on forge.

**Comment by Shibva** [comment]
sorry typo, I mean does this exist in a forge version
