### ISSUE TITLE
Unable to obtain Sincere Loyalty

### ISSUE THREAD

**Issue by RubyRezal** [Ladysnake/Impaled#13]
Minecraft 1.18.1
Fabric 0.12.12
Impaled 1.0.2

Following instructions on the Wiki, I'm trying to obtain "Sincere Loyalty" on tridents but this doesn't seem to be working. Tested in custom modpack and in a clean sandbox, same results.
![2022-01-09_14 22 43](https://user-images.githubusercontent.com/1816386/148698071-3c9d20e5-78e8-4d17-998e-feff204e69fb.png)
![2022-01-09_14 22 34](https://user-images.githubusercontent.com/1816386/148698073-c05b3104-5852-4a85-8742-25120d618de1.png)
![2022-01-09_14 22 39](https://user-images.githubusercontent.com/1816386/148698076-29b85e8a-d156-4811-af36-448ea2d63369.png)

Example images from modpack.

Don't know how helpful this might be, but here's my log from testing in a clean client. Same results as the modpack, couldn't upgrade any Loyalty III Trident to Loyalty IV.
https://mclo.gs/UNwQziw

**Comment by SinsOfVirtue** [comment]
You're trying to use an anvil, try doing the same thing with a smithing table instead!

**Comment by Xastabus** [comment]
![2022-01-24_08 19 50](https://user-images.githubusercontent.com/1816386/150791692-ec3cfd4f-b98b-4188-9959-e9b66a957f46.png)

Right... Why do I keep forgetting the smithing table is a thing?

Also, I seem to have been trying an outdated recipe?  Also, also, why didn't I look this up in REI in the first place?

The world may never know...

**Comment by RubyRezal** [comment]
![2022-01-24_08 40 07](https://user-images.githubusercontent.com/1816386/150793123-21ad1d9f-3d5a-418b-b382-f26a06bd84cd.png)

Thank you!
