### ISSUE TITLE
Incompatible with 1.18.2

### ISSUE THREAD

**Issue by Fourbo** [Ladysnake/Impaled#15]
Unfortunately 1.18.2 breaks compatibility with this mod, and the mod crashes on start-up. No other mods/datapacks were used, and this was tested on an Aternos server with Fabric Loader 13.3.

**Log file:**
https://gist.github.com/Fourbo/21c20fa5660c9128fdaad14d4c151215

**Mods used:**
fabric-api-0.48.0+1.18.2.jar
impaled-1.0.2.jar

**Comment by MoriyaShiine** [comment]
https://github.com/Ladysnake/Impaled/commit/dd7fc00f981f55383e9487d4ccdfa30b5f26783e
