### ISSUE TITLE
v1.1.4 not loading on 1.19.2

### ISSUE THREAD

**Issue by Mehechiger** [Ladysnake/Impaled#42]
Forge version 43.1.23
the mod is not loading, and I searched "impaled" in the log and found nothing.
Please let me know if I need to provide other info.

**Comment by Xiribidus** [comment]
Impaled is for fabric

**Comment by Mehechiger** [comment]
Ah.. any chance that you’d port to forge?

**Comment by Xiribidus** [comment]
No, sorry, Ladysnake mods are all either fabric or quilt.
