### ISSUE TITLE
What is the LICENSE of this project?

### ISSUE THREAD

**Issue by jwaxy** [Ladysnake/Impaled#49]
It says All rights reserved on modrinth but can I modify it a bit and use it in my private server?

**Comment by SekoiaTree** [comment]
Somebody correct me if I'm wrong, but "All Rights Reserved" means that Ladysnake decides what can and can't be done with *other people distributing it and modified versions*. However, by using it server-side on a private server, you're not distributing it, and you are allowed to modify that. However, you're not allowed to publish that anywhere without Ladysnake's permission.
