### ISSUE TITLE
Fabric Loader 0.11.3 / snapshot-21w18a - crashes as soon as any of the tridents are thrown.

### ISSUE THREAD

**Issue by CredibleToast** [Ladysnake/Impaled#6]
all trident that were added by impaled cause immediate crashes. 
[crash-2021-05-11_11.33.43-server.txt](https://github.com/Ladysnake/Impaled/files/6461318/crash-2021-05-11_11.33.43-server.txt)

**Comment by doctor4t** [comment]
Impaled is for 20w14a, over that snapshot nothing is guaranteed, but I'll update it.
